//! Phase 9 Brownfield extraction: typed candidate, confidence, and
//! coupling-score helpers shared across `cairn init --from-code`,
//! `cairn refine`, and the suggest engine.
//!
//! Submodules:
//! - `heuristics`: coupling score, confidence buckets, `Candidate` type
//! - `onboard`: orphan grouping and classification
//! - `discovery`: filesystem traversal for cold-start candidate extraction
//! - `init`: `cairn init --from-code` handler
//! - `refine`: `cairn refine` handler

/// Brownfield discovery: filesystem traversal for module candidates.
pub mod discovery;
mod heuristics;
/// Brownfield init: cold-start extraction from existing code.
pub mod init;
/// Brownfield onboarding: orphan grouping and classification.
pub mod onboard;
/// Brownfield refine: periodic re-discovery with timestamped changes.
pub mod refine;

pub use heuristics::{
    CONFIDENCE_HIGH, CONFIDENCE_MEDIUM, Candidate, CandidateConfidence, DIRECTORY_DEPTH_LIMIT,
    EDGE_OBSERVATION_THRESHOLD, MIN_CANDIDATE_FILE_COUNT, classify_score, coupling_score,
};

use crate::error::CairnError;
use discovery::{DiscoveredCandidate, Extraction};

/// Generate a stub contract for a discovered candidate.
#[must_use]
pub fn stub_contract(candidate: &DiscoveredCandidate) -> String {
    format!(
        "---\nnode: {}\n---\n# {}\n\n{}",
        candidate.id, candidate.name, candidate.description
    )
}

/// Write a brownfield change directory with proposal, blueprint delta,
/// and stub contracts.
///
/// # Errors
///
/// Returns `CairnError::WriteOutput` when any file cannot be written.
pub fn write_change(
    root: &std::path::Path,
    change_id: &str,
    extraction: &Extraction,
) -> Result<(), CairnError> {
    let change_dir = root.join("openspec/changes").join(change_id);
    create_dir(&change_dir)?;
    create_dir(&change_dir.join("contracts"))?;

    let proposal = format!(
        "# Proposal: {change_id}\n\nGenerated by brownfield extraction.\n\n## Candidates\n\n",
    );
    write_file(&change_dir.join("proposal.md"), &proposal)?;

    let delta = blueprint_delta(extraction);
    write_file(&change_dir.join("blueprint.delta"), &delta)?;

    for candidate in &extraction.candidates {
        let contract = stub_contract(candidate);
        let file_name = format!("{}.md", candidate.id.replace('.', "_"));
        write_file(&change_dir.join("contracts").join(file_name), &contract)?;
    }

    Ok(())
}

/// Render a blueprint delta from an extraction result.
#[must_use]
pub fn blueprint_delta(extraction: &Extraction) -> String {
    let mut lines = vec!["# Blueprint delta\n".to_owned()];
    for candidate in &extraction.candidates {
        lines.push(format!(
            "+ {} \"{}\" id \"{}\" {{",
            node_kind_from_path(&candidate.path),
            candidate.name,
            candidate.id
        ));
        lines.push(format!("    path \"{}\"", candidate.path));
        for edge in &candidate.edges {
            lines.push(format!(
                "    edge -> {} \"{}\"",
                edge.target, edge.description
            ));
        }
        lines.push("}\n".to_owned());
    }
    lines.join("\n")
}

fn node_kind_from_path(path: &str) -> &'static str {
    let segments: Vec<&str> = path.split(['/', '\\']).collect();
    if segments.iter().any(|s| *s == "api" || *s == "service") {
        "Container"
    } else {
        "Module"
    }
}

fn create_dir(path: &std::path::Path) -> Result<(), CairnError> {
    std::fs::create_dir_all(path).map_err(|e| CairnError::WriteOutput {
        path: path.to_string_lossy().to_string(),
        detail: e.to_string(),
    })
}

fn write_file(path: &std::path::Path, content: &str) -> Result<(), CairnError> {
    std::fs::write(path, content).map_err(|e| CairnError::WriteOutput {
        path: path.to_string_lossy().to_string(),
        detail: e.to_string(),
    })
}
