//! Phase 9 Brownfield extraction: typed candidate, confidence, and
//! coupling-score helpers shared across `cairn init --from-code`,
//! `cairn refine`, and the suggest engine.
//!
//! Submodules:
//! - `heuristics`: coupling score, confidence buckets, `Candidate` type
//! - `onboard`: orphan grouping and classification
//! - `discovery`: filesystem traversal for cold-start candidate extraction
//! - `init`: `cairn init --from-code` handler
//! - `refine`: `cairn refine` handler

/// Brownfield discovery: filesystem traversal for module candidates.
pub mod discovery;
mod heuristics;
/// Brownfield init: cold-start extraction from existing code.
pub mod init;
/// Brownfield interview runner: multi-round elicitation session.
pub mod interview;
/// Brownfield onboarding: orphan grouping and classification.
pub mod onboard;
/// Brownfield refine: periodic re-discovery with timestamped changes.
pub mod refine;
/// Brownfield suggest engine: cross-cutting edge inference.
pub mod suggest;
/// Brownfield summariser integration: builds bounded inputs from candidates.
pub mod summarise;
/// Brownfield templated authoring: contract template resolution.
pub mod templates;

pub use heuristics::{
    CONFIDENCE_HIGH, CONFIDENCE_MEDIUM, Candidate, CandidateConfidence, DIRECTORY_DEPTH_LIMIT,
    EDGE_OBSERVATION_THRESHOLD, MIN_CANDIDATE_FILE_COUNT, classify_score, coupling_score,
};

use crate::error::CairnError;
use discovery::{DiscoveredCandidate, Extraction};
use std::fmt::Write as _;

/// Generate a stub contract for a discovered candidate.
#[must_use]
pub fn stub_contract(candidate: &DiscoveredCandidate) -> String {
    format!(
        "---\noperation: added\nnode: {}\n---\n# {}\n\n{}\n",
        candidate.id,
        candidate.name,
        candidate.description.trim_end()
    )
}

/// Write a brownfield change directory with proposal, blueprint delta,
/// and stub contracts.
///
/// # Errors
///
/// Returns `CairnError::WriteOutput` when any file cannot be written.
pub fn write_change(
    root: &std::path::Path,
    change_id: &str,
    extraction: &Extraction,
    templates: &[templates::ContractTemplate],
) -> Result<(), CairnError> {
    let change_dir = root.join("meta/changes").join(change_id);
    create_dir(&change_dir)?;
    create_dir(&change_dir.join("contracts"))?;

    let mut proposal = format!(
        "# Proposal: {change_id}\n\nGenerated by brownfield extraction.\n\n## Candidates\n\n",
    );
    if extraction.candidates.is_empty() {
        proposal.push_str("_No module candidates discovered._\n");
    }
    for candidate in &extraction.candidates {
        let _ = writeln!(
            proposal,
            "- `{}` ({}) at `{}` (confidence {:.2})",
            candidate.id, candidate.name, candidate.path, candidate.confidence
        );
    }
    write_file(&change_dir.join("proposal.md"), &proposal)?;

    let delta = blueprint_delta(extraction);
    write_file(&change_dir.join("blueprint.delta"), &delta)?;

    for candidate in &extraction.candidates {
        let contract = templates::render_stub(candidate, templates);
        let file_name = format!("{}.md", candidate.id.replace('.', "_"));
        write_file(&change_dir.join("contracts").join(file_name), &contract)?;
    }

    suggest::write_suggested_edges(&change_dir, extraction, "phase-9-brownfield", "propose")?;

    Ok(())
}

/// Render a blueprint delta from an extraction result.
#[must_use]
pub fn blueprint_delta(extraction: &Extraction) -> String {
    let mut out = String::new();
    if !extraction.candidates.is_empty() {
        out.push_str("## ADDED Nodes\n");
        for candidate in &extraction.candidates {
            let path = format!("./{}", candidate.path);
            let _ = writeln!(
                out,
                "{} {} {:?} id {:?} {{",
                node_kind_from_path(&candidate.path),
                bareword(&candidate.name),
                candidate.description,
                candidate.id,
            );
            let _ = writeln!(out, "    path {path:?}");
            out.push_str("}\n\n");
        }
    }
    let mut edges = String::new();
    for candidate in &extraction.candidates {
        for edge in &candidate.edges {
            let _ = writeln!(
                edges,
                "{} -> {} {:?}",
                candidate.id, edge.target, edge.description
            );
        }
    }
    if !edges.is_empty() {
        out.push_str("## ADDED Edges\n");
        out.push_str(&edges);
        out.push('\n');
    }
    out
}

fn node_kind_from_path(path: &str) -> &'static str {
    let segments: Vec<&str> = path.split(['/', '\\']).collect();
    if segments.iter().any(|s| *s == "api" || *s == "service") {
        "Container"
    } else {
        "Module"
    }
}

/// Convert a discovered display name into a single bareword token. The blueprint
/// grammar's node-name slot is a bareword, not a string, so a multi-word name
/// like "api gateway" must collapse to "`ApiGateway`" to parse.
fn bareword(name: &str) -> String {
    let mut out = String::new();
    for word in name.split(|c: char| !c.is_alphanumeric()) {
        let mut chars = word.chars();
        if let Some(first) = chars.next() {
            out.extend(first.to_uppercase());
            out.push_str(chars.as_str());
        }
    }
    if out.is_empty() {
        "Module".to_owned()
    } else {
        out
    }
}

fn create_dir(path: &std::path::Path) -> Result<(), CairnError> {
    std::fs::create_dir_all(path).map_err(|e| CairnError::WriteOutput {
        path: path.to_string_lossy().to_string(),
        detail: e.to_string(),
    })
}

fn write_file(path: &std::path::Path, content: &str) -> Result<(), CairnError> {
    std::fs::write(path, content).map_err(|e| CairnError::WriteOutput {
        path: path.to_string_lossy().to_string(),
        detail: e.to_string(),
    })
}

#[cfg(test)]
mod tests {
    use super::*;
    use discovery::{DiscoveredCandidate, DiscoveredEdge, Extraction};

    fn candidate(id: &str, name: &str, path: &str) -> DiscoveredCandidate {
        DiscoveredCandidate {
            id: id.to_owned(),
            name: name.to_owned(),
            description: "Handles payments".to_owned(),
            path: path.to_owned(),
            tags: Vec::new(),
            confidence: 0.9,
            evidence: Vec::new(),
            edges: Vec::new(),
        }
    }

    fn extraction(candidates: Vec<DiscoveredCandidate>) -> Extraction {
        Extraction {
            candidates,
            schema_version: 1,
        }
    }

    // ── stub_contract ─────────────────────────────────────────────────────────

    #[test]
    fn test_stub_contract_ends_with_newline() {
        // Without a trailing \n the written file would fail POSIX convention
        // and could cause the frontmatter parser to drop the last line.
        let c = candidate("app.payments", "Payments", "payments/");
        let contract = stub_contract(&c);
        assert!(
            contract.ends_with('\n'),
            "stub_contract output must end with newline, got: {contract:?}"
        );
    }

    #[test]
    fn test_stub_contract_frontmatter_contains_node_id() {
        let c = candidate("app.payments", "Payments", "payments/");
        let contract = stub_contract(&c);
        assert!(
            contract.contains("node: app.payments"),
            "frontmatter must have node id: {contract:?}"
        );
    }

    #[test]
    fn test_stub_contract_body_has_h1_name() {
        let c = candidate("app.payments", "Payments", "payments/");
        let contract = stub_contract(&c);
        assert!(
            contract.contains("# Payments"),
            "body must contain H1 node name: {contract:?}"
        );
    }

    #[test]
    fn test_stub_contract_body_contains_description() {
        let mut c = candidate("app.payments", "Payments", "payments/");
        c.description = "Handles payment processing".to_owned();
        let contract = stub_contract(&c);
        assert!(
            contract.contains("Handles payment processing"),
            "body must contain description: {contract:?}"
        );
    }

    // ── node_kind_from_path ───────────────────────────────────────────────────

    #[test]
    fn test_node_kind_api_segment_is_container() {
        assert_eq!(node_kind_from_path("src/api"), "Container");
    }

    #[test]
    fn test_node_kind_service_segment_is_container() {
        assert_eq!(node_kind_from_path("service/auth"), "Container");
    }

    #[test]
    fn test_node_kind_api_alone_is_container() {
        assert_eq!(node_kind_from_path("api"), "Container");
    }

    #[test]
    fn test_node_kind_apigateway_is_module_not_container() {
        // "apigateway" is a single segment that does not equal "api";
        // node_kind_from_path checks exact segment equality only.
        assert_eq!(node_kind_from_path("apigateway"), "Module");
    }

    #[test]
    fn test_node_kind_regular_path_is_module() {
        assert_eq!(node_kind_from_path("src/payments"), "Module");
    }

    #[test]
    fn test_node_kind_backslash_path_api_is_container() {
        assert_eq!(node_kind_from_path("src\\api"), "Container");
    }

    // ── blueprint_delta ───────────────────────────────────────────────────────

    #[test]
    fn test_blueprint_delta_empty_extraction_is_empty() {
        let delta = blueprint_delta(&extraction(vec![]));
        assert!(
            delta.is_empty(),
            "empty extraction must produce no delta sections: {delta:?}"
        );
    }

    #[test]
    fn test_blueprint_delta_single_candidate_no_edges() {
        let c = candidate("app.payments", "Payments", "payments/");
        let delta = blueprint_delta(&extraction(vec![c]));
        assert!(
            delta.contains("## ADDED Nodes"),
            "delta must use the canonical ADDED Nodes header: {delta:?}"
        );
        assert!(
            delta.contains(r#"Module Payments "Handles payments" id "app.payments""#),
            "must contain a canonical node declaration: {delta:?}"
        );
        assert!(
            delta.contains(r#"path "./payments/""#),
            "must contain path: {delta:?}"
        );
        assert!(
            !delta.contains("## ADDED Edges"),
            "no edges expected: {delta:?}"
        );
    }

    #[test]
    fn test_blueprint_delta_edge_in_canonical_edges_section() {
        let mut c = candidate("app.payments", "Payments", "payments/");
        c.edges.push(DiscoveredEdge {
            target: "app.auth".to_owned(),
            description: "auth dep".to_owned(),
            confidence: 0.8,
        });
        let delta = blueprint_delta(&extraction(vec![c]));
        assert!(
            delta.contains("## ADDED Edges"),
            "delta must use the canonical ADDED Edges header: {delta:?}"
        );
        assert!(
            delta.contains(r#"app.payments -> app.auth "auth dep""#),
            "edge must appear in canonical form: {delta:?}"
        );
    }

    #[test]
    fn test_blueprint_delta_api_path_uses_container_kind() {
        let c = candidate("app.api", "Api", "src/api");
        let delta = blueprint_delta(&extraction(vec![c]));
        assert!(
            delta.contains("Container Api "),
            "api path must produce Container kind: {delta:?}"
        );
    }

    #[test]
    fn test_blueprint_delta_multiword_name_collapses_to_bareword() {
        // The grammar's node-name slot is a bareword, so a discovered name with
        // spaces must collapse or the emitted delta will not parse.
        let c = candidate("app.api_gw", "api gateway", "src/api_gw");
        let delta = blueprint_delta(&extraction(vec![c]));
        assert!(
            delta.contains(r"ApiGateway "),
            "multi-word name must collapse to a bareword: {delta:?}"
        );
    }
}
