//! `cairn refine` implementation.
//!
//! Re-runs brownfield discovery and writes results to a timestamped
//! change directory under `meta/changes/brownfield-refine-{secs}/`.

use std::path::Path;

use crate::error::CairnError;

use super::discovery::Extraction;

/// Fixed change ID prefix for refine extractions.
const CHANGE_ID_PREFIX: &str = "brownfield-refine";

/// Run brownfield refine, creating a timestamped change directory
/// with the latest discovery results.
///
/// If a change directory with the same timestamp already exists, a
/// numeric suffix is appended to avoid silent overwrites.
///
/// # Errors
///
/// Returns `CairnError::ChangeDiscovery` when filesystem operations fail.
pub fn run_refine(root: &Path) -> Result<String, CairnError> {
    let extraction = super::discovery::discover(root)?;
    let change_id = unique_change_id(root, &timestamp())?;
    let templates = super::templates::load_templates(root);
    write_refine_change(root, &change_id, &extraction, &templates)?;
    Ok(change_id)
}

/// Produces a unique change ID by appending a counter suffix when the
/// directory already exists.
fn unique_change_id(root: &Path, ts: &str) -> Result<String, CairnError> {
    let base = format!("{CHANGE_ID_PREFIX}-{ts}");
    let changes_dir = root.join("meta/changes");
    if !changes_dir.join(&base).exists() {
        return Ok(base);
    }
    for counter in 1..=999u32 {
        let candidate = format!("{base}-{counter}");
        if !changes_dir.join(&candidate).exists() {
            return Ok(candidate);
        }
    }
    Err(CairnError::ChangeDiscovery {
        path: changes_dir.to_string_lossy().to_string(),
        detail: format!("could not find unique change ID after 999 attempts for {base}"),
    })
}

fn timestamp() -> String {
    use std::time::{SystemTime, UNIX_EPOCH};
    let nanos = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .unwrap_or_default()
        .as_nanos();
    nanos.to_string()
}

/// Write a brownfield refine change directory with proposal, blueprint delta,
/// and stub contracts. The delta may include renames, additions, and removals
/// when an existing blueprint is present.
///
/// # Errors
///
/// Returns `CairnError::WriteOutput` when any file cannot be written.
fn write_refine_change(
    root: &Path,
    change_id: &str,
    extraction: &Extraction,
    templates: &[super::templates::ContractTemplate],
) -> Result<(), CairnError> {
    let change_dir = root.join("meta/changes").join(change_id);
    super::create_dir(&change_dir)?;
    super::create_dir(&change_dir.join("contracts"))?;

    let (renames, removals) = detect_renames_and_removals(root, extraction);

    let proposal = format!(
        "# Proposal: {change_id}\n\nGenerated by brownfield refinement.\n\n## Candidates\n\n",
    );
    super::write_file(&change_dir.join("proposal.md"), &proposal)?;

    let delta = blueprint_delta_with_renames(extraction, &renames, &removals);
    super::write_file(&change_dir.join("blueprint.delta"), &delta)?;

    for candidate in &extraction.candidates {
        let contract = super::templates::render_stub(candidate, templates);
        let file_name = format!("{}.md", candidate.id.replace('.', "_"));
        super::write_file(&change_dir.join("contracts").join(file_name), &contract)?;
    }

    super::suggest::write_suggested_edges(
        &change_dir,
        extraction,
        "phase-9-brownfield",
        "propose",
    )?;

    Ok(())
}

/// Detect renames and removals by comparing discovered candidates against
/// the existing blueprint. A rename is emitted when an existing node's path
/// no longer exists on disk but a new candidate appears in the same parent
/// directory with a similar name.
fn detect_renames_and_removals(
    root: &Path,
    extraction: &Extraction,
) -> (Vec<(String, String)>, Vec<String>) {
    let blueprint_path = root.join("cairn.blueprint");
    if !blueprint_path.exists() {
        return (Vec::new(), Vec::new());
    }

    let Ok(ast) = crate::blueprint::parse_file(&blueprint_path) else {
        return (Vec::new(), Vec::new());
    };

    let existing_nodes = flatten_nodes(&ast.nodes);
    let candidate_paths: std::collections::BTreeSet<&str> = extraction
        .candidates
        .iter()
        .map(|c| c.path.as_str())
        .collect();

    let mut renames = Vec::new();
    let mut removals = Vec::new();

    for (id, path) in &existing_nodes {
        let full_path = root.join(path);
        if full_path.exists() || candidate_paths.contains(path.as_str()) {
            continue;
        }

        // Path no longer exists. Look for a candidate in the same parent dir.
        let parent = path.rsplit_once('/').map(|(p, _)| p);
        let mut rename_found = false;
        for candidate in &extraction.candidates {
            let cand_parent = candidate.path.rsplit_once('/').map(|(p, _)| p);
            if parent == cand_parent {
                // Same parent directory: treat as rename.
                renames.push((id.clone(), candidate.id.clone()));
                rename_found = true;
                break;
            }
        }

        if !rename_found {
            removals.push(id.clone());
        }
    }

    (renames, removals)
}

/// Flatten all nodes from the AST into a list of (id, path) pairs.
fn flatten_nodes(nodes: &[crate::blueprint::Node]) -> Vec<(String, String)> {
    let mut result = Vec::new();
    for node in nodes {
        if let Some(path) = node.paths.first() {
            result.push((node.id.clone(), path.clone()));
        }
        result.extend(flatten_nodes(&node.children));
    }
    result
}

/// Render a blueprint delta from an extraction result, including renames
/// and removals detected against the existing blueprint.
fn blueprint_delta_with_renames(
    extraction: &Extraction,
    renames: &[(String, String)],
    removals: &[String],
) -> String {
    let mut lines = vec!["# Blueprint delta\n".to_owned()];

    for (from, to) in renames {
        lines.push(format!("~ {from} -> {to}"));
    }

    for id in removals {
        lines.push(format!("- {id}"));
    }

    for candidate in &extraction.candidates {
        lines.push(format!(
            "+ {} \"{}\" id \"{}\" {{",
            super::node_kind_from_path(&candidate.path),
            candidate.name,
            candidate.id
        ));
        lines.push(format!("    path \"{}\"", candidate.path));
        for edge in &candidate.edges {
            lines.push(format!(
                "    edge -> {} \"{}\"",
                edge.target, edge.description
            ));
        }
        lines.push("}\n".to_owned());
    }

    lines.join("\n")
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::blueprint::{NodeKind, Span};
    use crate::brownfield::discovery::{DiscoveredCandidate, DiscoveredEdge, Extraction};

    fn span() -> Span {
        Span::point("test", 1, 1)
    }

    fn bare_node(id: &str, paths: &[&str]) -> crate::blueprint::Node {
        crate::blueprint::Node {
            kind: NodeKind::Module,
            id: id.to_owned(),
            name: id.to_owned(),
            description: String::new(),
            tags: Vec::new(),
            paths: paths.iter().map(|s| (*s).to_owned()).collect(),
            owns_files: false,
            contracts: Vec::new(),
            raw_fields: Vec::new(),
            children: Vec::new(),
            span: span(),
        }
    }

    fn candidate(id: &str, path: &str) -> DiscoveredCandidate {
        DiscoveredCandidate {
            id: id.to_owned(),
            name: id.to_owned(),
            description: String::new(),
            path: path.to_owned(),
            tags: Vec::new(),
            confidence: 1.0,
            evidence: Vec::new(),
            edges: Vec::new(),
        }
    }

    fn empty_extraction() -> Extraction {
        Extraction {
            candidates: Vec::new(),
            schema_version: 1,
        }
    }

    // ── flatten_nodes ─────────────────────────────────────────────────────────

    #[test]
    fn test_flatten_nodes_empty_list_returns_empty() {
        assert!(flatten_nodes(&[]).is_empty());
    }

    #[test]
    fn test_flatten_nodes_node_with_path_included() {
        let node = bare_node("app.api", &["src/api"]);
        let result = flatten_nodes(&[node]);
        assert_eq!(result, vec![("app.api".to_owned(), "src/api".to_owned())]);
    }

    #[test]
    fn test_flatten_nodes_node_without_path_skipped() {
        let node = bare_node("app.api", &[]);
        let result = flatten_nodes(&[node]);
        assert!(result.is_empty(), "node with no paths must be skipped");
    }

    #[test]
    fn test_flatten_nodes_multiple_paths_uses_only_first() {
        let node = bare_node("app.api", &["src/api", "src/api/v2"]);
        let result = flatten_nodes(&[node]);
        assert_eq!(result.len(), 1);
        assert_eq!(result[0].1, "src/api", "only the first path must be used");
    }

    #[test]
    fn test_flatten_nodes_includes_children_recursively() {
        let mut parent = bare_node("app", &["src"]);
        parent.children = vec![bare_node("app.api", &["src/api"])];
        let result = flatten_nodes(&[parent]);
        assert_eq!(result.len(), 2);
        let ids: Vec<&str> = result.iter().map(|(id, _)| id.as_str()).collect();
        assert!(ids.contains(&"app"), "parent must be included");
        assert!(ids.contains(&"app.api"), "child must be included");
    }

    // ── blueprint_delta_with_renames ──────────────────────────────────────────

    #[test]
    fn test_delta_empty_extraction_produces_only_header() {
        let out = blueprint_delta_with_renames(&empty_extraction(), &[], &[]);
        assert!(
            out.starts_with("# Blueprint delta"),
            "must start with header: {out:?}"
        );
        // No candidate sections.
        assert!(
            !out.contains("+ "),
            "no candidate lines for empty extraction: {out:?}"
        );
    }

    #[test]
    fn test_delta_rename_produces_tilde_line() {
        let out = blueprint_delta_with_renames(
            &empty_extraction(),
            &[("old.node".to_owned(), "new.node".to_owned())],
            &[],
        );
        assert!(
            out.contains("~ old.node -> new.node"),
            "rename line: {out:?}"
        );
    }

    #[test]
    fn test_delta_removal_produces_dash_line() {
        let out = blueprint_delta_with_renames(&empty_extraction(), &[], &["dead.node".to_owned()]);
        assert!(out.contains("- dead.node"), "removal line: {out:?}");
    }

    #[test]
    fn test_delta_candidate_produces_plus_section() {
        let mut ext = empty_extraction();
        ext.candidates = vec![candidate("src.api", "src/api")];
        let out = blueprint_delta_with_renames(&ext, &[], &[]);
        assert!(
            out.contains("+ "),
            "candidate section must start with +: {out:?}"
        );
        assert!(
            out.contains(r#"id "src.api""#),
            "candidate id quoted: {out:?}"
        );
        assert!(out.contains(r#"path "src/api""#), "path line: {out:?}");
    }

    #[test]
    fn test_delta_candidate_with_api_segment_is_container() {
        // A path containing the segment "api" must produce "Container" kind.
        // Any other path must produce "Module".
        let mut ext = empty_extraction();
        ext.candidates = vec![candidate("src.api", "src/api")];
        let out = blueprint_delta_with_renames(&ext, &[], &[]);
        assert!(out.contains("+ Container"), "api-path → Container: {out:?}");

        let mut ext2 = empty_extraction();
        ext2.candidates = vec![candidate("src.worker", "src/worker")];
        let out2 = blueprint_delta_with_renames(&ext2, &[], &[]);
        assert!(out2.contains("+ Module"), "non-api-path → Module: {out2:?}");
    }

    #[test]
    fn test_delta_candidate_with_edge_produces_edge_line() {
        let mut cand = candidate("src.a", "src/a");
        cand.edges = vec![DiscoveredEdge {
            target: "src.b".to_owned(),
            description: "sibling module".to_owned(),
            confidence: 1.0,
        }];
        let mut ext = empty_extraction();
        ext.candidates = vec![cand];
        let out = blueprint_delta_with_renames(&ext, &[], &[]);
        assert!(
            out.contains(r#"edge -> src.b "sibling module""#),
            "edge line: {out:?}"
        );
    }

    // ── unique_change_id ──────────────────────────────────────────────────────

    #[test]
    fn test_unique_change_id_returns_base_when_no_collision() {
        let dir = tempfile::tempdir().expect("temp dir");
        let root = dir.path();
        // Don't create meta/changes/ at all — base must not exist.
        let result = unique_change_id(root, "99999").expect("must succeed");
        assert_eq!(result, format!("{CHANGE_ID_PREFIX}-99999"));
    }

    #[test]
    fn test_unique_change_id_appends_1_when_base_exists() {
        let dir = tempfile::tempdir().expect("temp dir");
        let root = dir.path();
        let ts = "12345";
        let base = format!("{CHANGE_ID_PREFIX}-{ts}");
        std::fs::create_dir_all(root.join("meta/changes").join(&base)).unwrap();
        let result = unique_change_id(root, ts).expect("must succeed");
        assert_eq!(result, format!("{base}-1"));
    }

    #[test]
    fn test_unique_change_id_skips_to_2_when_base_and_1_both_exist() {
        let dir = tempfile::tempdir().expect("temp dir");
        let root = dir.path();
        let ts = "67890";
        let base = format!("{CHANGE_ID_PREFIX}-{ts}");
        let changes = root.join("meta/changes");
        std::fs::create_dir_all(changes.join(&base)).unwrap();
        std::fs::create_dir_all(changes.join(format!("{base}-1"))).unwrap();
        let result = unique_change_id(root, ts).expect("must succeed");
        assert_eq!(result, format!("{base}-2"));
    }
}
