//! `cairn refine` implementation.
//!
//! Re-runs brownfield discovery and writes results to a timestamped
//! change directory under `openspec/changes/brownfield-refine-{secs}/`.

use std::path::Path;

use crate::error::CairnError;

use super::discovery::Extraction;

/// Fixed change ID prefix for refine extractions.
const CHANGE_ID_PREFIX: &str = "brownfield-refine";

/// Run brownfield refine, creating a timestamped change directory
/// with the latest discovery results.
///
/// If a change directory with the same timestamp already exists, a
/// numeric suffix is appended to avoid silent overwrites.
///
/// # Errors
///
/// Returns `CairnError::ChangeDiscovery` when filesystem operations fail.
pub fn run_refine(root: &Path) -> Result<String, CairnError> {
    let extraction = super::discovery::discover(root)?;
    let change_id = unique_change_id(root, &timestamp())?;
    let templates = super::templates::load_templates(root);
    write_refine_change(root, &change_id, &extraction, &templates)?;
    Ok(change_id)
}

/// Produces a unique change ID by appending a counter suffix when the
/// directory already exists.
fn unique_change_id(root: &Path, ts: &str) -> Result<String, CairnError> {
    let base = format!("{CHANGE_ID_PREFIX}-{ts}");
    let changes_dir = root.join("openspec/changes");
    if !changes_dir.join(&base).exists() {
        return Ok(base);
    }
    for counter in 1..=999u32 {
        let candidate = format!("{base}-{counter}");
        if !changes_dir.join(&candidate).exists() {
            return Ok(candidate);
        }
    }
    Err(CairnError::ChangeDiscovery {
        path: changes_dir.to_string_lossy().to_string(),
        detail: format!("could not find unique change ID after 999 attempts for {base}"),
    })
}

fn timestamp() -> String {
    use std::time::{SystemTime, UNIX_EPOCH};
    let nanos = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .unwrap_or_default()
        .as_nanos();
    nanos.to_string()
}

/// Write a brownfield refine change directory with proposal, blueprint delta,
/// and stub contracts. The delta may include renames, additions, and removals
/// when an existing blueprint is present.
///
/// # Errors
///
/// Returns `CairnError::WriteOutput` when any file cannot be written.
fn write_refine_change(
    root: &Path,
    change_id: &str,
    extraction: &Extraction,
    templates: &[super::templates::ContractTemplate],
) -> Result<(), CairnError> {
    let change_dir = root.join("openspec/changes").join(change_id);
    super::create_dir(&change_dir)?;
    super::create_dir(&change_dir.join("contracts"))?;

    let (renames, removals) = detect_renames_and_removals(root, extraction);

    let proposal = format!(
        "# Proposal: {change_id}\n\nGenerated by brownfield refinement.\n\n## Candidates\n\n",
    );
    super::write_file(&change_dir.join("proposal.md"), &proposal)?;

    let delta = blueprint_delta_with_renames(extraction, &renames, &removals);
    super::write_file(&change_dir.join("blueprint.delta"), &delta)?;

    for candidate in &extraction.candidates {
        let contract = super::templates::render_stub(candidate, templates);
        let file_name = format!("{}.md", candidate.id.replace('.', "_"));
        super::write_file(&change_dir.join("contracts").join(file_name), &contract)?;
    }

    super::suggest::write_suggested_edges(
        &change_dir,
        extraction,
        "phase-9-brownfield",
        "propose",
    )?;

    Ok(())
}

/// Detect renames and removals by comparing discovered candidates against
/// the existing blueprint. A rename is emitted when an existing node's path
/// no longer exists on disk but a new candidate appears in the same parent
/// directory with a similar name.
fn detect_renames_and_removals(
    root: &Path,
    extraction: &Extraction,
) -> (Vec<(String, String)>, Vec<String>) {
    let blueprint_path = root.join("cairn.blueprint");
    if !blueprint_path.exists() {
        return (Vec::new(), Vec::new());
    }

    let Ok(ast) = crate::blueprint::parse_file(&blueprint_path) else {
        return (Vec::new(), Vec::new());
    };

    let existing_nodes = flatten_nodes(&ast.nodes);
    let candidate_paths: std::collections::BTreeSet<&str> = extraction
        .candidates
        .iter()
        .map(|c| c.path.as_str())
        .collect();

    let mut renames = Vec::new();
    let mut removals = Vec::new();

    for (id, path) in &existing_nodes {
        let full_path = root.join(path);
        if full_path.exists() || candidate_paths.contains(path.as_str()) {
            continue;
        }

        // Path no longer exists. Look for a candidate in the same parent dir.
        let parent = path.rsplit_once('/').map(|(p, _)| p);
        let mut rename_found = false;
        for candidate in &extraction.candidates {
            let cand_parent = candidate.path.rsplit_once('/').map(|(p, _)| p);
            if parent == cand_parent {
                // Same parent directory: treat as rename.
                renames.push((id.clone(), candidate.id.clone()));
                rename_found = true;
                break;
            }
        }

        if !rename_found {
            removals.push(id.clone());
        }
    }

    (renames, removals)
}

/// Flatten all nodes from the AST into a list of (id, path) pairs.
fn flatten_nodes(nodes: &[crate::blueprint::Node]) -> Vec<(String, String)> {
    let mut result = Vec::new();
    for node in nodes {
        if let Some(path) = node.paths.first() {
            result.push((node.id.clone(), path.clone()));
        }
        result.extend(flatten_nodes(&node.children));
    }
    result
}

/// Render a blueprint delta from an extraction result, including renames
/// and removals detected against the existing blueprint.
fn blueprint_delta_with_renames(
    extraction: &Extraction,
    renames: &[(String, String)],
    removals: &[String],
) -> String {
    let mut lines = vec!["# Blueprint delta\n".to_owned()];

    for (from, to) in renames {
        lines.push(format!("~ {from} -> {to}"));
    }

    for id in removals {
        lines.push(format!("- {id}"));
    }

    for candidate in &extraction.candidates {
        lines.push(format!(
            "+ {} \"{}\" id \"{}\" {{",
            super::node_kind_from_path(&candidate.path),
            candidate.name,
            candidate.id
        ));
        lines.push(format!("    path \"{}\"", candidate.path));
        for edge in &candidate.edges {
            lines.push(format!(
                "    edge -> {} \"{}\"",
                edge.target, edge.description
            ));
        }
        lines.push("}\n".to_owned());
    }

    lines.join("\n")
}
